=head1 NAME

BSE::Password - interface for password hashing and checking.

=head1 SYNOPSIS

  my $pass_handler = BSE::Password::Foo->new;
  my $hash = $pass_handler->hash($password);
  if ($pass_handler->check($hash, $password)) {
    # success
  }

=head1 DESCRIPTION

This module implements a simple mechanism for hashing passwords.

Sub-classes should implement three methods:

=over

=item new()

Create a new handler.  Should return nothing if this mechanism is not
available, eg. if modules required to implement it aren't available.

=item hash($password)

Return a hash to store for later checks.

=item check($hash, $password)

Check that the password matches the hash.  Return true on a match.

=back

=head1 AUTHOR

Tony Cook <tony@develop-help.com>

=cut
