=head1 NAME

access.pod - access control for administration of BSE

=head1 SYNOPSIS

The implementation of access control for BSE.

=head1 DESCRIPTION

The aim is to provide flexible access control, without requiring
micro-management from the administrators.

Since we want to be control a user's access to specific fields
(eg. the template and parent fields), rather than having an admin have
to setup specific access to those fields, we want some sort of "macro"
mechansim to control several things at once.

Some possible access macros could be:

=over

=item *

allow editing body and title of an article

=item *

add an article, with everything fixed, except for title and body

=item *

allow changes to everything but the shop

=item *

allow changes only to the shop

=back

We also need to be able to separately control whole trees, rather than
just specific articles, so it should be possible to refer to "all
descendants of article foo".

Possible article permissions:

=over

=item *

add child

=item *

modify

=item *

modify field I<foo>

=item *

add image

=item *

reorder children

=item *

delete

=item *

delete image

=item *

change image details

=back

=head1 MACRO PERMISSIONS

These would be split into two types of macro permissions, those that
control specific articles, and those that are applied to an article.

Each macro will need to be described in bse.cfg, and the name of the
macro assigned an index so that it can be controlled.

Since most normal permissions aren't going to be directly useful, the
only permissions stored in the system will be macro based permissions.

=head2 Attached macros

These name one or more articles and the permissions can be different
for each article.

=head2 Unattached macros

These supply a set of permissions to some article specified through
the administration interface.

=head1 GROUPS

To make it simpler to control permissions, each user belongs to one of
more groups, each of which only supplied positive permissions.

Whether or not listed in the group, each user is in the "everyone"
group.

=head1 DEFAULT PERMISSIONS

The everyone group, and the administrator user, both have the macro
"Full Access" on all descendants of article -1.


=head1 MACRO STORAGE

To simplify processing we have two sections in the config file:

=over

=item *

[Global permissions] - keeps permissions that have all article
references resolved

=item *

[Article permissions] - permissions which have to reference an article

=back

The [permission ids] section is used to translate permission indexes to
permission ids.

The [permission names] section is used to translate permission indexes
to descriptive permission names.

=head1 PERMISSIONS REFERENCE

=head2 Article editing

=over

=item *

edit_add_child

The user can add a child to this article, or reparent an article to
have this article as a parent.

=item *

edit_field_edit_I<fieldname>

The user can edit the given field in an existing article.

=item *

edit_field_add_I<fieldname>

The user can edit the give field when creating a new article.  These
permissions are applied to the parent where articles might be added.

For fields that the user doesn't have permission for, either the value
from the [children of I<parentid>] section, the [level I<level>]
section, or some default value will be used.

=back

=head2 User/Group Administration

=over

=item *

admin_*

=back

=cut

