=head1 NAME

BSE - an engine for simple magazine style WWW sites.

=head1 DESCRIPTION

BSE is an engine for creating simple magazine stype web sites.

Maybe I'll add some other bits here.

=head1 CHANGES

=head2 0.11_05

This is a test release.

=over

=item *

added base_tags() to BSE::Custom (tags available during static
generation of most pages.)

=item *

step(kids|parents) now available to all articles, though you may have
some problems connecting the shop articles (catalogs,products) to
others

=item *

standard date tag available in most places

=item *

the <:summary:> tag now takes an optional which parameter, defaulting
to "child".

=item *

you can now specify the default template for children of a given
article.

=item *

you can specify extra template directories to search while editing a
given article.

=item *

moved the side bar logon form to it's own article (loaded by
initial.pl) and added it to the side bar subsection.

=item *

shortened the long message used in the refresh back to user.pl when
the user has file based products in their cart, but hasn't logged in.
This was causing problems with IE6.  It now attempts to pull a longer
message out of the config file.

=back

=head2 0.11_03

=over

=item *

handling of downloads from the user page is handled better: you don't
get a download link unless the file is downloadable, and rejected
download results in a refresh to the user page rather than just
displaying the user page

=item *

the logon and register pages can now be passed a refresh url, which
the shop uses when it refreshes to the logon page

=item *

add an orders button when logged in

=item *

the file list was messed up

=back

=head2 0.11_02

Another test release:

=over

=item *

actually tested the form filling with the user's defaults

=item *

modify localinst.perl to remove the default bse.cfg

=item *

have the checkout function return if the user needs to register (shop.pl)

=item *

check in a few more places if the user needs to register (shop.pl)

=item *

changed names of fields in SiteUsers to match the checkout form

=item *

added telephone and facsimile fields to the user options

=back

=head2 0.11_01

Test release:

=over

=item *

supports files attached to products for sale

=item *

user registration

=item *

we now have a config file

=back

=head2 0.11

Looks like all known problems are fixed.  Time to do a semi-major
release.

=head2 0.10_16

=over

=item *

hopefully fixed an occasionaly problem where the images would reorder
themselves

=back

=head2 0.10_15

=over

=item *

make the depth parameter in <:embed which template depth:> work

=item *

give the sitemap a lower depth since 7 levels (5 + the level1 and 2)
is too much.

=back

=head2 0.10_14

=over

=item *

try to avoid dividing entered prices by 100 when there's an error on
the product edit/add form.  There's still some potential problems
here, but they're much less likely to cause a problem.

=item *

remove the border from image[] generated images

=item *

move the error message on the product add form so it isn't mixed up
with the menu

=item *

the dummy product used to generate the product edit form after an
error wasn't useful for getting step catalogs, get the real product
object just for that.

=back

=head2 0.10_13

=over

=item *

remove the border from embedded images with a url

=item *

fixed an old bug that defaulted the threshold from the template (oops)

=item *

the ... in <:image which align ...:> or <:image which field ...:> is
now appended to the attributes of the image field.  If it includes a
border attribute the default border attribute is suppressed.

=back

=head2 0.10_12

=over

=item *

new order_list templates from adrian (moved the filter forms into the table)

=item *

fixed the image wizard for products.  I'm suprised this ever worked.
Wasn't preserving parentid when creating a new product.

=item *

new edit_product template from adrian

=item *

stupid bug in BSE::Shop::Util

=item *

email is now in BSE::CustomBase->required_fields() and can be removed
by BSE::Custom->required_fields().  If it is removed then no
validation of the email address is performed.

=item *

state changes made in handling the confirm page are now saved

=item *

added strict to a few modules

=item *

added missing error handling methods to BSE::Mail.

=item *

old tag on the confirm tag now never gives the undef value message

=item *

if you specify a embedding depth less than the current maximum, you
won't get an error message embedded when passing that depth.  This
lets you do more interesting effects.

=item *

shop.pl now writes mail sending errors to STDERR (to the error log on
apache) rather than aborting the order display (since the order
actually exists at this point.)

=back

=head2 0.10_11

=over

=item *

support for filtering the order lists by dates entered by the user

=item *

make the add section link work, and make the link itself a little more 
usable

=item *

removed some old debug code

=item *

make BSE::Custom->checkout_actions() work on the confirmation page

=back

=head2 0.10_10

=over

=item *

documented new tags for Product.pm and Article.pm

=item *

shopadmin.pl can list/move the stepkids (you can hide them too)

=item *

added some tests to test if various iterators show anything,
ifProducts, ifAnyProds, ifStepProds.

=back

=head2 0.10_09

=over

=item *

put the reorder links into the edit templates

=item *

fix expire labels for edit_1.tmpl and edit_catalog.tmpl

=item *

reordering from the catalog works

=item *

reordering from the product editor works

=back

=head2 0.10_08

Making progress.

=over

=item *

fixed the ordering of items in the allprods tag

=item *

make allprods always work with products

=item *

realware wanted a confirmation page

=back

=head2 0.10_07

Another test release:

=over

=item *

initial step kids|parents for the shop

=item *

new popup menu templates from Adrian

=item *

added acknowledgements to AUTHOR section

=back

=head2 0.10_06

Test release for Adrian, with his new templates.

=head2 0.10_05

Test release for Adrian.

=head2 0.10_04

Don't use this version.

=over

=item *

URLs can be directly associated with an image

=item *

multiple levels of catalogs

=item *

shop item options

=item *

filtering/sorting of orders from the template

=item *

embedded templates can be based on the template of the article being
embedded

=item *

order status information, marking an order has having been filled

=item *

better handling of generation errors

=item *

partial support for Microsoft SQL Server under IIS

=item *

extended price tag for the cart and checkout pages

=item *

prePurchase target for the shop, to allow custom credit card processing

=item *

template based filtering of the order list

=back

=head2 0.10_03

=over

=item *

added the admin/reorder.pl script

=item *

template names in <: embed :> tags have $ replaced with the template
name of the article.

=back

=head2 0.10_02

=over

=item *

added the image[] tag  (image[index|align|url])

=item *

added printable.pl, site/templates/printable/printable.tmpl to allow
printable versions of pages (among other things)

=item *

implemented the ifCurrentPage tag

=back

=head2 0.10_01

=over

=item *

added <:siteUrl:> tag in %EXTRA_TAGS (used by the RSS templates)

=item *

fixed broken template value for the formatting guide (initial.pl)

=item *

fixed broken admin links for the formatting guide (initial.pl)

=item *

the formatting guide now generates to
http://your.site/a/format_guide.html (initial.pl)

=item *

RDF/RSS is now generated to /a/site.rdf.  This includes links and
titles for the articles on the home page, and a search field (if the
tool displaying the RSS supports that.)

=back

=head2 0.10

WARNING: the tag for articles found for a search has changed from:

  article I<field>

to:

  result I<field>

There is a new module required: HTML::Parser

=over 4

=item *

the <:embed child:> tags meaning has been expanded to allow embedding
of any article with an optional template

=item *

there's now an embed[] tag for use in body text.  Both this and 
<:embed ... :> are protected against infinite recursion.

=item *

changed display values for sections etc in Constants.pm, you can still
put your own in when you customize.

=item *

the default templates for each level have been set to a single
template, for a simpler default setup

=item *

new admin index pages, which may display a little better in some
browsers

=item *

you can move articles between levels, if enabled in Constants.pm

=item *

unquoted search terms will do "start of word" searches if enabled in 
Constants.pm

=item *

html[] tags and <html> body text now has tags stripped when displayed
as a summary or as a search excerpt.  The search indexing can now
handle both of these too.

=item *

the search template now uses 'result' rather than 'article' for the
search result entries.  This is needed since the search base page is
generated as an article, using a dummy article.  The title and
titleImage for this dummy article can be specified in Constants.pm.

=item *

you can now control whether an unlisted level1 article is displayed in
the crumbs for an article.  By default unlisted level1 articles are
NOT listed anymore.

=item *

a bunch of new templates from adrian, including moving the common
layout into base.tmpl where possible, support for "sidebars".

=item *

a formatting guide article in initial.pl (from adrian) (and then an
updated version of it)

=item *

renamed INSTALL to INSTALL.txt to prevent wierdness if someone tries
"make install" on a case-insensitive file system.

=item *

administration templates are now kept in the admin directory in the
templates directory

=item *

added simple test installer.  WARNING: this destroys the existing content
of your site.

=item *

distribution now includes site/htdocs/shop as a directory rather than
as a file

=item *

schema/bse.sql now drops the tables if they already exist

=item *

the item description in the shopping cart is now a link to the item

=item *

changed some defaults in Constants.pm

=item *

catalog templates from $TMPLDIR/templates/catalogs weren't being handled
correctly

=back

=head2 0.09

=over 4

=item *

added support for controlling access to the regenerate option

=item *

added the ability to disable auto-regeneration

this initially broke some buttons, fixed

=item *

properly escape child properties in add.pl

=item *

removing an article now removes any associated images

=item *

removing an image from an article now removes the image file when you
save the article.

=item *

added datadump.pl (send an email containing a mysql datadump), with
configuration in Constants.pm

=item *

added imageclean.pl - cleans up the image table and images directory

=item *

added an advanced admin page with links to datadump.pl and
imageclean.pl (you can change these of course).

=item *

previously it was possible for a user with admin rights to choose a
template that was outside the templates directory.  

=back

=head2 0.08

=over 4

=item *

modified administration templates

=item *

formatting is now stripped from body text before an excerpt is
produced (for the search results).

=back

=head2 0.07

I'll add in the 0.07 change list as soon as I figure out what I changed...

Once I get my old 0.08 RC that may include the 0.07 change list.

=head2 0.06

Some changes are being made to allow the engine to be embedded into a
site (specifically squirrelweb.com.au).

=over 4

=item *

Bug fix: shop.pl had a silly exporter mistake, and a sillier reference
to an unknown variable name.

=item *

changed admin links to buttons for the catalog and product pages,
added a Display button to the product page.

=item *

cleaned up the shopitem, cart_base, checkout_base, checkoutfinal_base,
mailorder and mailconfirm templates, removing tags that don't work in
them, removing references to bodyscoop, fixing broken images, removed
thawte stamp.gif.

=item *

%EXTRA_TAGS now work in mailorder and mailconfirm templates

=item *

You can now use $SHOP_EMAIL_ORDER to disable sending the encrypted
order.  (Useful only for testing or until you get encryption keys
organized - there's no other way to get the credit card number and
expiry date.)

=item *

Generate/Product.pm had a hard-coded link to the internal test
site. (Doh!)

=item *

some base URIs can be configured, though this still needs some work.

=back

=head2 0.05

=over 4

=item *

Bug fix: only add the class attribute to thumbnails if one is supplied
(doh!)

=item *

Moved shop configuration from shop.pl to Constants.pm

=item *

Extended template field to 127 characters so directories can be used
without chopping off names.

=item *

Added installation documentation.

=item *

Templates in the drop-down lists in add.pl now includes templates from
$TMPLDIR/$level and $TMPLDIR/common.

=item *

crumbs now include the section, whether or not they are listed.

=item *

added templates.pod, which contains most templating documentation,
copied from new documentation in various places (shop.pl, search.pl,
Generate::*.pm).

=item *

search.pl wasn't handling single-quoted search terms correctly

=item *

added ifInMenu tag

=item *

more changes to support multiple catalogs:

=over 4

=item *

the initial catalog can be removed.  The initial catalog isn't useful
when you need more than one catalog.  If you want multiple catalogs
you need to remove the initial catalog and then add new ones.  The
templates need work too.

=item *

the link/admin fields for the new article are set correctly (oops)

=item *

added a sample section template for a multi-catalog shop

=back

=item *

the sample templates look better, along with better title images

=item *

the shop was being generated with a non-secure url

=item *

parent articles were not being regenerated when an article was deleted

=back

=head2 0.04

You will need to recreate the articles table, since a new column has
been added to support article thumbnails.

=over 4

=item *

Added article thumbnails.

=item *

Multiple product catalogs.

=item *

leadTime is now modifiable in products.

=item *

Bug fix: only list .tmpl files from template directories in article
editing forms.

=item *

Bug fix: prevent adding non-catalog subsections to the shop section.

=item *

Bug fix: the crumbs iterator no longer shows crumbs that have "don't
list in menu" set.  Such subsections often shouldn't be linked to.

=item *

The documentation on article templates has been improved.

=item *

Some tags that operate on articles have been expanded to work on all
article objects available in the template.

=back

=head1 AUTHOR

Tony Cook <tony@develop-help.com>

I originally wrote BSE while an employee at SquirrelWeb
(http://www.squirrelgroup.com/) for one of VisualThought's clients,
bodyScoop.com (http://www.bodyScoop.com.au/).

Most of the BSE templates were created by Adrian Oldham of Visual
Thought Communications (http://www.visualthought.com.au) He also
funded and suggested many improvements.

Realware Systems (http://www.realware.com.au/) funded the nested
catalogs, IIS support, the image access tags, and many other shop
improvements, including most of the BSE::Custom hooks.

=cut
