=head1 NAME

paypal.pod - processing payments through PayPal with BSE.

=head1 SYNOPSIS

  [shop]
  payment_types=4
  ; or for both CC and paypal:
  payment_types=0,4

  [paypal]
  test=0
  live_api_username=...
  live_api_password=...
  live_api_signature=...

  ; or for testing - THIS IS THE DEFAULT
  test=1
  test_api_username=...
  test_api_password=...
  test_api_signature=...

  [paypal custom]
  ; see the PayPal ExpressCheckout Advanced Feature Guide
  HDRBORDERCOLOR=...
  HDRBACKCOLOR=...
  PAGESTYLE=...
  HDRIMG=...
  LOCALECODE=...

