=head1 NAME

thumbnails.pod - thumbnail images for BSE's image manager

=head1 SYNOPSIS

How to configure thumbnails for BSE image manager.

=head1 DESCRIPTION

If configured, the image manager will display thumbnails for each of
the images attached to the article instead of displaying the images
fullsize inline.

If you don't want thumbnail make sure you configure them off or supply
the C<f_showfull> parameter, since some processing is done whenever a
<:thumbimage:> tag is seen, even if that tag is on the false side of
an <:if ...:>.

=head1 INSTALLATION

You will need to install the perl Imager package, it's possible your
operating system includes packages for this module.

Otherwise install Imager from CPAN:

=over

=item 1

install the libraries that Imager depends on, this is at least
libjpeg, libgif (or libungif) and libpng.  You can also install
libtiff, but this shouldn't be necessary, since TIFF isn't a common
web format.

All of these libraries are usually available in your operating
system's packaging system, or are preinstalled.

=item 2

install Imager, as root:

  perl -MCPAN -eshell
  # you may be prompted here if you haven't run the shell before
  > install Imager

=back

If you have problems with the tiff tests for Imager, you will need to
either disable tiff support in Imager, or use the following tiff.c:

  http://www.develop-help.com/imager/src/tiff.c

Once you have Imager installed, add the following to bse.cfg (or
bse-local.cfg):

[editor]
allow_thumb=1
thumbs_class=BSE::Thumb::Imager

If you don't see thumbnails on the image manager page, check your
server error log file for error messages.

=head1 AUTHOR

Tony Cook <tony@develop-help.com>

=head1 REVISION

$Revision$

=cut
