#!perl -w
use strict;
use Test::More tests => 38;
use_ok("BSE::Cfg");
use_ok("Squirrel::Template");
use_ok("BSE::Template");
use_ok("BSE::Util::PasswordValidate");
use_ok("DevHelp::Date");
use_ok("DevHelp::Formatter");
use_ok("DevHelp::HTML");
use_ok("DevHelp::Validate");
use_ok("BSE::Variables");
use_ok("BSE::TB::AuditLog");
use_ok("BSE::TB::Tag");
use_ok("BSE::TB::Tags");
use_ok("BSE::TB::TagCategory");
use_ok("BSE::TB::TagCategories");
use_ok("BSE::TB::TagOwner");
use_ok("BSE::TB::TagOwners");
use_ok("BSE::TB::Article");
use_ok("BSE::TB::Articles");
use_ok('BSE::Generate');
use_ok('BSE::Generate::Article');
use_ok('BSE::Generate::Product');
use_ok('BSE::Generate::Catalog');
use_ok('BSE::Edit::Article');
use_ok('BSE::Edit::Site');
use_ok('BSE::Edit::Catalog');
use_ok('BSE::Edit::Product');
use_ok('BSE::Edit::Seminar');
use_ok("BSE::UI::Page");
use_ok("BSE::UserReg");
use_ok("BSE::Index");
use_ok("BSE::Index::BSE");
use_ok("BSE::ImageClean");
use_ok("BSE::UI::AdminImageClean");
use_ok("BSE::UI::Thumb");
use_ok("BSE::UI::Interest");
use_ok("BSE::Request::Base");
use_ok("BSE::Request");
use_ok("BSE::Request::Test");

my $builder = Test::Builder->new;
$builder->is_passing or $builder->BAIL_OUT;
